New dropdown and padding fix
fradesa/FlutterBoringForm pull request #3
Opened 2023-02-03 16:27 UTC by enzo-desimone

- Add new drop down field with optional search
- Change form head label padding

2023-02-14 16:59 UTC, enzo-desimone commented
- Add CopyWith for all Fields
- Add Boring Table Fields
- Add Boring Table

2023-02-14 23:17 UTC, fradesa requested changes
Set explicit type in 'copyWith' overrides

2023-02-14 23:19 UTC, fradesa commented
Quando fai ad esempio l'override dentro a BoringTextField dovrebbe essere così:

`
@override
BoringTextFIeld copyWith(....
`

Non lasciamo il generico BoringFIeld che tanto è estesa

2023-02-14 23:19 UTC, fradesa commented
Tutto il resto è ottimo!

2023-02-15 08:05 UTC, enzo-desimone commented
Done!

2023-02-15 08:05 UTC, enzo-desimone commented
> Set explicit type in 'copyWith' overrides

Done!

2023-02-15 08:44 UTC, fradesa approved these changes

2023-02-15 08:44 UTC, merged